baseURL = 'https://natalielim.github.io/hugo-mock-landing-page/'
title = "Stitched Social"
author = "Natalie Lim"
copyright = "Natalie Lim"

timeZone = 'America/New_York'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
# themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  # comment out unused taxonomies
  # tag = "tags"
  # series = "series"
  # category = "categories"
  # author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

# Disable RSS feed generation
disableKinds = ["RSS", "taxonomy", "term"]

# Disable unused output formats
[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
